[
  {
    "type": "NO_MIB",
    "trap": "systemStarted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.1",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "sysContact": 5,
      "sysName": 6,
      "sysLocation": 7,
      "pduSerialNumber": 8,
      "pduNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The system has started.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "systemReset",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.2",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9,
      "pduNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The system was rebooted.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userLogin",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.3",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user logged in.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userLogout",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.4",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user logged out.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userAuthenticationFailure",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.5",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user authentication attempt failed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userSessionTimeout",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.8",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user session timed out.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userAdded",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.11",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "targetUser": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user account was added to the system.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userModified",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.12",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "targetUser": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user account was modified.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userDeleted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.13",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "targetUser": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user account was deleted from the system.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "roleAdded",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.14",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "roleName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A role was added to the system.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "roleModified",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.15",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "roleName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A role was modified.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "roleDeleted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.16",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "roleName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A role was deleted from the system.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "deviceUpdateStarted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.20",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "imageVersion": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11,
      "pduNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The device firmware update has started.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "deviceUpdateCompleted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.21",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "imageVersion": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11,
      "pduNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "ok",
      "description": "The device firmware update has completed.",
      "mib_name": "PDU2-MIB",
      "base_trap_name": "deviceUpdated"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userBlocked",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.22",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A blocked user tried to log in.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "powerControl",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.23",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "outletLabel": 7,
      "measurementsOutletSensorState": 8,
      "switchingOperation": 9,
      "sysContact": 10,
      "sysName": 11,
      "sysLocation": 12,
      "pduSerialNumber": 13,
      "pduNumber": 14
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An outlet switching operation has been performed. Note that measurementsOutletSensorState represents the state of the outlet at the time the trap was sent. This may be different from the final state of the outlet. For instance, if the outlet is cycled and the outlet cycle delay is 20 seconds, this variable will indicate OFF although the final state of the outlet will be ON. The final state of the outlet will be indicated in the outletSensorStateChange trap for the outlet onOff sensor.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userPasswordChanged",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.24",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "targetUser": 3,
      "pxIPAddress": 4,
      "pxInetAddressType": 5,
      "pxInetIPAddress": 6,
      "agentInetPortNumber": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "User password was changed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "passwordSettingsChanged",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.28",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Strong password settings changed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "firmwareValidationFailed",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.38",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9,
      "pduNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Validation of an uploaded firmware image failed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "logFileCleared",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.41",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "ok",
      "description": "The event log has been cleared.",
      "mib_name": "PDU2-MIB",
      "base_trap_name": "logFileed"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "bulkConfigurationSaved",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.53",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A bulk configuration file was downloaded from the device.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "bulkConfigurationCopied",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.54",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A bulk configuration file was copied to the device.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "pduSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.60",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "typeOfSensor": 6,
      "measurementsUnitSensorTimeStamp": 7,
      "measurementsUnitSensorValue": 8,
      "measurementsUnitSensorState": 9,
      "measurementsUnitSensorSignedValue": 10,
      "oldSensorState": 11,
      "sysContact": 12,
      "sysName": 13,
      "sysLocation": 14,
      "pduSerialNumber": 15
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Unit-level sensor state change. Which value field to use depends on the metadata of the sensor. measurementsUnitSensorValue is undefined for sensors which can have negative readings, measurementsUnitSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.61",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "inletLabel": 6,
      "typeOfSensor": 7,
      "measurementsInletSensorTimeStamp": 8,
      "measurementsInletSensorValue": 9,
      "measurementsInletSensorState": 10,
      "measurementsInletSensorSignedValue": 11,
      "oldSensorState": 12,
      "sysContact": 13,
      "sysName": 14,
      "sysLocation": 15,
      "pduSerialNumber": 16
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Inlet sensor state change. Which value field to use depends on the metadata of the sensor. measurementsInletSensorValue is undefined for sensors which can have negative readings, measurementsInletSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings. For an rcmState sensor transitioning to the fail state, the value is the residual current just before the sensor transitioned to the fail state i.e. if typeOfSensor = rcmState and measurementsInletSensorState = fail, then measurementsInletSensorValue = the residual current just before the sensor transitioned to the fail state",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletPoleSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.62",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "inletLabel": 6,
      "inletPoleNumber": 7,
      "typeOfSensor": 8,
      "measurementsInletPoleSensorTimeStamp": 9,
      "measurementsInletPoleSensorValue": 10,
      "measurementsInletPoleSensorState": 11,
      "measurementsInletPoleSensorSignedValue": 12,
      "oldSensorState": 13,
      "sysContact": 14,
      "sysName": 15,
      "sysLocation": 16,
      "pduSerialNumber": 17
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Inlet pole sensor state change. Which value field to use depends on the metadata of the sensor. measurementsInletPoleSensorValue is undefined for sensors which can have negative readings, measurementsInletPoleSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.63",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "outletLabel": 6,
      "typeOfSensor": 7,
      "measurementsOutletSensorTimeStamp": 8,
      "measurementsOutletSensorValue": 9,
      "measurementsOutletSensorState": 10,
      "measurementsOutletSensorSignedValue": 11,
      "oldSensorState": 12,
      "sysContact": 13,
      "sysName": 14,
      "sysLocation": 15,
      "pduSerialNumber": 16
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Outlet sensor state change. Which value field to use depends on the metadata of the sensor. measurementsOutletSensorValue is undefined for sensors which can have negative readings, measurementsOutletSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletPoleSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.64",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "outletLabel": 6,
      "outletPoleNumber": 7,
      "typeOfSensor": 8,
      "measurementsOutletPoleSensorTimeStamp": 9,
      "measurementsOutletPoleSensorValue": 10,
      "measurementsOutletPoleSensorState": 11,
      "measurementsOutletPoleSensorSignedValue": 12,
      "oldSensorState": 13,
      "sysContact": 14,
      "sysName": 15,
      "sysLocation": 16,
      "pduSerialNumber": 17
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Outlet pole sensor state change. Which value field to use depends on the metadata of the sensor. measurementsOutletPoleSensorValue is undefined for sensors which can have negative readings, measurementsOutletPoleSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "overCurrentProtectorSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.65",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "overCurrentProtectorLabel": 6,
      "typeOfSensor": 7,
      "measurementsOverCurrentProtectorSensorTimeStamp": 8,
      "measurementsOverCurrentProtectorSensorValue": 9,
      "measurementsOverCurrentProtectorSensorState": 10,
      "measurementsOverCurrentProtectorSensorSignedValue": 11,
      "oldSensorState": 12,
      "sysContact": 13,
      "sysName": 14,
      "sysLocation": 15,
      "pduSerialNumber": 16,
      "suspectedTripCauseLabel": 17
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Overcurrent protector sensor state change. Which value field to use depends on the metadata of the sensor. measurementsOverCurrentProtectorSensorValue is undefined for sensors which can have negative readings, measurementsOverCurrentProtectorSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings. For trip sensor state changes, if a particular outlet is determined to be likely to have caused the OCP trip, its label is passed in suspectedTripCauseLabel. For an rcmState sensor transitioning to the fail state, the value is the residual current just before the sensor transitioned to the fail state.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "externalSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.66",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "externalSensorNumber": 6,
      "typeOfSensor": 7,
      "measurementsExternalSensorTimeStamp": 8,
      "measurementsExternalSensorValue": 9,
      "measurementsExternalSensorState": 10,
      "oldSensorState": 11,
      "externalSensorSerialNumber": 12,
      "externalOnOffSensorSubtype": 13,
      "externalSensorChannelNumber": 14,
      "sysContact": 15,
      "sysName": 16,
      "sysLocation": 17,
      "pduSerialNumber": 18,
      "externalSensorName": 19
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "External sensor state change.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "smtpMessageTransmissionFailure",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.67",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "smtpMessageRecipients": 5,
      "smtpServer": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "SMTP message transmission failure",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "ldapError",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.68",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "errorDescription": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An LDAP error occurred; errorDescription describes the error",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "deviceUpdateFailed",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.70",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "imageVersion": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The device firmware update has failed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "loadSheddingModeEntered",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.71",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9,
      "pduNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The PDU has entered load shedding mode",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "loadSheddingModeExited",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.72",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9,
      "pduNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The PDU has exited load shedding mode",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "pingServerEnabled",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.73",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "serverIPAddress": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The ping feature has been enabled for a server.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "pingServerDisabled",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.74",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "serverIPAddress": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The ping feature has been disabled for a server.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "serverNotReachable",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.75",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "serverIPAddress": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A monitored server has become unreachable.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "serverReachable",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.76",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "serverIPAddress": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A monitored server has become reachable.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "rfCodeTagConnected",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.77",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "sysContact": 5,
      "sysName": 6,
      "sysLocation": 7,
      "pduSerialNumber": 8
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An RF-Code tag has been connected.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "rfCodeTagDisconnected",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.78",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "sysContact": 5,
      "sysName": 6,
      "sysLocation": 7,
      "pduSerialNumber": 8
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An RF-Code tag has been disconnected.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "deviceIdentificationChanged",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.79",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "userName": 5,
      "deviceChangedParameter": 6,
      "changedParameterNewValue": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11,
      "pduNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A device identification parameter has been changed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "usbExpansionUnitConnected",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.80",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "sysContact": 5,
      "sysName": 6,
      "sysLocation": 7,
      "pduSerialNumber": 8
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Connectivity to downstream expansion unit has been established. It applies to the following interfaces: USB Ethernet This trap is sent only if deviceCascadeType is portForwarding",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "usbExpansionUnitDisconnected",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.81",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "sysContact": 5,
      "sysName": 6,
      "sysLocation": 7,
      "pduSerialNumber": 8
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Connectivity to downstream expansion unit has been lost It applies to the following interfaces: USB Ethernet This trap is sent only if deviceCascadeType is portForwarding",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "lhxSupportChanged",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.82",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "lhxSupportEnabled": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Schroff LHX support has been enabled or disabled.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userAcceptedRestrictedServiceAgreement",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.83",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user accepted the Restricted Service Agreement.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userDeclinedRestrictedServiceAgreement",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.84",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user declined the Restricted Service Agreement.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "wireSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.85",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "wireLabel": 6,
      "typeOfSensor": 7,
      "measurementsWireSensorTimeStamp": 8,
      "measurementsWireSensorValue": 9,
      "measurementsWireSensorState": 10,
      "oldSensorState": 11,
      "sysContact": 12,
      "sysName": 13,
      "sysLocation": 14,
      "pduSerialNumber": 15
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Wire sensor state change.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "transferSwitchSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.86",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "transferSwitchLabel": 6,
      "typeOfSensor": 7,
      "measurementsTransferSwitchSensorTimeStamp": 8,
      "measurementsTransferSwitchSensorValue": 9,
      "measurementsTransferSwitchSensorState": 10,
      "measurementsTransferSwitchSensorSignedValue": 11,
      "oldSensorState": 12,
      "sysContact": 13,
      "sysName": 14,
      "sysLocation": 15,
      "transferSwitchLastTransferReason": 16,
      "pduSerialNumber": 17
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Transfer switch sensor state change. Which value field to use depends on the metadata of the sensor. measurementsTransferSwitchSensorValue is undefined for sensors which can have negative readings, measurementsTransferSwitchSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "deviceSettingsSaved",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.88",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A configuration backup has been downloaded from the device.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "deviceSettingsRestored",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.89",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxIPAddress": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A configuration backup has been restored to the device.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "webcamInserted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.90",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "webcamModel": 5,
      "webcamConnectionPort": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A webcam has been connected.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "webcamRemoved",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.91",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "webcamModel": 5,
      "webcamConnectionPort": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A webcam has been disconnected.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletEnabled",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.92",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "inletLabel": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "PDU operation has been enabled for an inlet",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletDisabled",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.93",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "inletLabel": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "PDU operation has been disabled for an inlet",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "serverConnectivityUnrecoverable",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.94",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "serverIPAddress": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The connection to a monitored server could not be recovered.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "radiusError",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.95",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "errorDescription": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A Radius error occurred; errorDescription describes the error",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "serverReachabilityError",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.96",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "serverIPAddress": 5,
      "errorDescription": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Server reachability error occurred; errorDescription describes the error. This trap is sent when the Error state is entered. Reasons for transitioning to the Error state include the following: Unable to resolve the server hostname.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletSensorReset",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.97",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pduNumber": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "inletLabel": 7,
      "typeOfSensor": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An inlet sensor was reset.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletSensorReset",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.98",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pduNumber": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "outletLabel": 7,
      "typeOfSensor": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An outlet sensor was reset.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "unknownPeripheralDeviceAttached",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.99",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "peripheralDeviceRomcode": 5,
      "peripheralDevicePackagePosition": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An unsupported peripheral device was attached.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "peripheralDeviceFirmwareUpdate",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.100",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "peripheralDevicePackageSerialNumber": 5,
      "peripheralDeviceFirmwareUpdateState": 6,
      "peripheralDevicePackageFirmwareVersion": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11,
      "pduNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The firmware update state of a peripheral device changed while performing update to peripheralDevicePackageFirmwareVersion.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "unitSensorReset",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.101",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pduNumber": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "typeOfSensor": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An unit sensor was reset.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "unitSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.102",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "typeOfSensor": 6,
      "measurementsUnitSensorTimeStamp": 7,
      "measurementsUnitSensorValue": 8,
      "measurementsUnitSensorState": 9,
      "measurementsUnitSensorSignedValue": 10,
      "oldSensorState": 11,
      "sysContact": 12,
      "sysName": 13,
      "sysLocation": 14,
      "pduSerialNumber": 15
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Unit-level sensor state change. Which value field to use depends on the metadata of the sensor. measurementsUnitSensorValue is undefined for sensors which can have negative readings, measurementsUnitSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "circuitSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.103",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "circuitNumber": 6,
      "typeOfSensor": 7,
      "measurementsCircuitSensorTimeStamp": 8,
      "measurementsCircuitSensorValue": 9,
      "measurementsCircuitSensorState": 10,
      "measurementsCircuitSensorSignedValue": 11,
      "oldSensorState": 12,
      "sysContact": 13,
      "sysName": 14,
      "sysLocation": 15,
      "pduSerialNumber": 16
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "BCM2/PMC branch circuit sensor state change. Which value field to use depends on the metadata of the sensor. measurementsCircuitSensorValue is undefined for sensors which can have negative readings, measurementsCircuitSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "circuitPoleSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.104",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "circuitNumber": 6,
      "circuitPoleNumber": 7,
      "typeOfSensor": 8,
      "measurementsCircuitPoleSensorTimeStamp": 9,
      "measurementsCircuitPoleSensorValue": 10,
      "measurementsCircuitPoleSensorState": 11,
      "measurementsCircuitPoleSensorSignedValue": 12,
      "oldSensorState": 13,
      "sysContact": 14,
      "sysName": 15,
      "sysLocation": 16,
      "pduSerialNumber": 17
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "BCM2/PMC circuit pole sensor state change. Which value field to use depends on the metadata of the sensor. measurementsCircuitPoleSensorValue is undefined for sensors which can have negative readings, measurementsCircuitPoleSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "circuitAdded",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.105",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "userName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "circuitNumber": 7,
      "circuitName": 8,
      "circuitType": 9,
      "circuitRatedCurrent": 10,
      "circuitCTRating": 11,
      "sysContact": 12,
      "sysName": 13,
      "sysLocation": 14,
      "pduSerialNumber": 15
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A new branch circuit has been configured",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "circuitDeleted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.106",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "userName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "circuitNumber": 7,
      "circuitName": 8,
      "circuitType": 9,
      "sysContact": 10,
      "sysName": 11,
      "sysLocation": 12,
      "pduSerialNumber": 13
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A configured branch circuit has been deleted",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "circuitModified",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.107",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "userName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "circuitNumber": 7,
      "circuitName": 8,
      "circuitType": 9,
      "circuitRatedCurrent": 10,
      "circuitCTRating": 11,
      "sysContact": 12,
      "sysName": 13,
      "sysLocation": 14,
      "pduSerialNumber": 15
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A configured branch circuit has been modified",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "circuitSensorReset",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.108",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pduNumber": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "circuitNumber": 7,
      "typeOfSensor": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An circuit sensor was reset.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "powerMeterAdded",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.109",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "userName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "powerMeterPhaseCTRating": 7,
      "powerMeterNeutralCTRating": 8,
      "powerMeterEarthCTRating": 9,
      "powerMeterPanelPositions": 10,
      "powerMeterPanelLayout": 11,
      "powerMeterPanelNumbering": 12,
      "powerMeterType": 13,
      "inletRatedCurrent": 14,
      "sysContact": 15,
      "sysName": 16,
      "sysLocation": 17,
      "pduSerialNumber": 18
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A new power meter or panel has been configured",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "powerMeterDeleted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.110",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "userName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "powerMeterType": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A configured power meter has been deleted",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "powerMeterModified",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.111",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "userName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "powerMeterPhaseCTRating": 7,
      "powerMeterNeutralCTRating": 8,
      "powerMeterEarthCTRating": 9,
      "powerMeterType": 10,
      "inletRatedCurrent": 11,
      "sysContact": 12,
      "sysName": 13,
      "sysLocation": 14,
      "pduSerialNumber": 15
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A configured power meter has been modified",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "smsMessageTransmissionFailure",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.112",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "phoneNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Sending an SMS message failed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "smartCardInserted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.113",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "smartCardReaderId": 5,
      "smartCardTimestamp": 6,
      "smartCardType": 7,
      "smartCardId": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12,
      "smartCardReaderManufacturer": 13,
      "smartCardReaderProduct": 14,
      "smartCardReaderSerialNumber": 15,
      "smartCardReaderChannel": 16,
      "smartCardReaderPosition": 17,
      "pduNumber": 18,
      "smartCardReaderName": 19,
      "smartCardReaderDescription": 20
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A smartcard was inserted into a card reader.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "smartCardRemoved",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.114",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "smartCardReaderId": 5,
      "smartCardTimestamp": 6,
      "smartCardType": 7,
      "smartCardId": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12,
      "smartCardReaderManufacturer": 13,
      "smartCardReaderProduct": 14,
      "smartCardReaderSerialNumber": 15,
      "smartCardReaderChannel": 16,
      "smartCardReaderPosition": 17,
      "pduNumber": 18,
      "smartCardReaderName": 19,
      "smartCardReaderDescription": 20
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A smartcard was removed from a card reader.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "rawConfigurationDownloaded",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.115",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9,
      "pduNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The raw configuration was downloaded from the device.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "rawConfigurationUpdated",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.116",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9,
      "pduNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A raw configuration update was applied on the device.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "hwFailureStatusChanged",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.117",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "sysContact": 5,
      "sysName": 6,
      "sysLocation": 7,
      "pduSerialNumber": 8,
      "hwFailureComponentId": 9,
      "hwFailureType": 10,
      "hwFailureAsserted": 11,
      "pduNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A hardware component's failure state has changed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletGroupAdded",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.118",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "outletGroupNumber": 3,
      "outletGroupName": 4,
      "pxInetAddressType": 5,
      "pxInetIPAddress": 6,
      "agentInetPortNumber": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A new outlet group has been configured",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletGroupModified",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.119",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "outletGroupNumber": 3,
      "outletGroupName": 4,
      "pxInetAddressType": 5,
      "pxInetIPAddress": 6,
      "agentInetPortNumber": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A configured outlet group has been modified",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletGroupDeleted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.120",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "outletGroupNumber": 3,
      "outletGroupName": 4,
      "pxInetAddressType": 5,
      "pxInetIPAddress": 6,
      "agentInetPortNumber": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A configured outlet group has been deleted",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletGroupSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.121",
    "trap-var-binds": {
      "pduName": 1,
      "outletGroupNumber": 2,
      "outletGroupName": 3,
      "pxInetAddressType": 4,
      "pxInetIPAddress": 5,
      "agentInetPortNumber": 6,
      "typeOfSensor": 7,
      "measurementsOutletGroupSensorTimeStamp": 8,
      "measurementsOutletGroupSensorValue": 9,
      "measurementsOutletGroupSensorState": 10,
      "measurementsOutletGroupSensorSignedValue": 11,
      "oldSensorState": 12,
      "sysContact": 13,
      "sysName": 14,
      "sysLocation": 15,
      "pduSerialNumber": 16
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Outlet group sensor state change. Which value field to use depends on the metadata of the sensor. measurementsOutletGroupSensorValue is undefined for sensors which can have negative readings, measurementsOutletGroupSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletGroupSensorReset",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.122",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "outletGroupNumber": 3,
      "outletGroupName": 4,
      "pxInetAddressType": 5,
      "pxInetIPAddress": 6,
      "agentInetPortNumber": 7,
      "typeOfSensor": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An outlet group sensor was reset.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletGroupPowerControl",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.123",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "outletGroupNumber": 3,
      "outletGroupName": 4,
      "outletGroupSwitchingOperation": 5,
      "pxInetAddressType": 6,
      "pxInetIPAddress": 7,
      "agentInetPortNumber": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An outlet group switching operation has been performed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "serverPowerControlInitiated",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.124",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "userName": 5,
      "serverIPAddress": 6,
      "serverPowerOperation": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A server power control operation was initiated.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "serverPowerControlCompleted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.125",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "serverIPAddress": 5,
      "serverPowerResult": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "ok",
      "description": "A server power control operation has completed.",
      "mib_name": "PDU2-MIB",
      "base_trap_name": "serverPowerControld"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "webcamStorageUploadStarted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.126",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "userName": 5,
      "webcamName": 6,
      "webcamFolderUrl": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11,
      "pduNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A new snapshot upload to webcam storage has started.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "testEventTriggered",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.127",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "userName": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A test event was triggered.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "actuatorSwitched",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.128",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "userName": 6,
      "externalSensorNumber": 7,
      "externalSensorName": 8,
      "externalSensorSerialNumber": 9,
      "externalOnOffSensorSubtype": 10,
      "externalSensorChannelNumber": 11,
      "typeOfSensor": 12,
      "actuatorState": 13,
      "sysContact": 14,
      "sysName": 15,
      "sysLocation": 16,
      "pduSerialNumber": 17
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An actuator control operation has been performed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "keypadPinEntered",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.129",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "keypadId": 6,
      "keypadPinTimestamp": 7,
      "keypadPin": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12,
      "keypadManufacturer": 13,
      "keypadProduct": 14,
      "keypadSerialNumber": 15,
      "keypadChannel": 16,
      "keypadPosition": 17,
      "keypadName": 18,
      "keypadDescription": 19
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A PIN was entered into a keypad.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "doorAccessGranted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.130",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "doorAccessRuleId": 5,
      "doorAccessRuleName": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Door access was granted.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "doorAccessDenied",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.131",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "doorAccessRuleId": 5,
      "doorAccessRuleName": 6,
      "doorAccessDenialReason": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Door access was denied.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "doorAccessRuleAdded",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.132",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "doorAccessRuleId": 6,
      "doorAccessRuleName": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A door access rule was added.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "doorAccessRuleChanged",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.133",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "doorAccessRuleId": 6,
      "doorAccessRuleName": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A door access rule was changed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "doorAccessRuleDeleted",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.134",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "doorAccessRuleId": 6,
      "doorAccessRuleName": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A door access rule was deleted.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletLinePairSensorStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.135",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "inletLabel": 6,
      "inletLinePairNumber": 7,
      "typeOfSensor": 8,
      "measurementsInletLinePairSensorTimeStamp": 9,
      "measurementsInletLinePairSensorValue": 10,
      "measurementsInletLinePairSensorState": 11,
      "measurementsInletLinePairSensorSignedValue": 12,
      "oldSensorState": 13,
      "sysContact": 14,
      "sysName": 15,
      "sysLocation": 16,
      "pduSerialNumber": 17
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Inlet line pair sensor state change. Which value field to use depends on the metadata of the sensor. measurementsInletLinePairSensorValue is undefined for sensors which can have negative readings, measurementsInletLinePairSensorSignedValue is undefined for sensors whose range exceeds the Integer32 range. Both fields do not apply to sensors without numerical readings.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "tacPlusError",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.136",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "errorDescription": 5,
      "sysContact": 6,
      "sysName": 7,
      "sysLocation": 8,
      "pduSerialNumber": 9
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A TACACS+ error occurred; errorDescription describes the error",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletSuspended",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.137",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "outletLabel": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10,
      "pduNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "An outlet was suspended after being suspected to have caused an OCP trip event.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "userRenamed",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.138",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "targetUser": 3,
      "newTargetUser": 4,
      "pxInetAddressType": 5,
      "pxInetIPAddress": 6,
      "agentInetPortNumber": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A user account was renamed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletDipEvent",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.151",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "inletLabel": 6,
      "dipSwellEventVoltage": 7,
      "dipSwellEventTimeStamp": 8,
      "dipSwellEventDuration": 9,
      "sysContact": 10,
      "sysName": 11,
      "sysLocation": 12,
      "pduSerialNumber": 13
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Dip event on the inlet voltage sensor.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletSwellEvent",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.152",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "inletLabel": 6,
      "dipSwellEventVoltage": 7,
      "dipSwellEventTimeStamp": 8,
      "dipSwellEventDuration": 9,
      "sysContact": 10,
      "sysName": 11,
      "sysLocation": 12,
      "pduSerialNumber": 13
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Dip event on the inlet voltage sensor.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletPoleDipEvent",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.153",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "inletLabel": 6,
      "inletPoleNumber": 7,
      "dipSwellEventVoltage": 8,
      "dipSwellEventTimeStamp": 9,
      "dipSwellEventDuration": 10,
      "sysContact": 11,
      "sysName": 12,
      "sysLocation": 13,
      "pduSerialNumber": 14
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Dip event on the voltage sensor of an inlet pole.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "inletPoleSwellEvent",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.154",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "inletLabel": 6,
      "inletPoleNumber": 7,
      "dipSwellEventVoltage": 8,
      "dipSwellEventTimeStamp": 9,
      "dipSwellEventDuration": 10,
      "sysContact": 11,
      "sysName": 12,
      "sysLocation": 13,
      "pduSerialNumber": 14
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Swell event on the voltage sensor of an inlet pole.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "portFuseStateChange",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.155",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "portFuseState": 5,
      "externalPortFuseId": 6,
      "externalPortName": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "The state of a port fuse changed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "linkUnitAdded",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.156",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "linkUnitId": 6,
      "linkUnitAddress": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A new link unit has been added.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "linkUnitReleased",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.157",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "linkUnitId": 6,
      "linkUnitAddress": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A link unit has been released.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "linkUnitCommunicationOk",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.158",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "linkUnitId": 5,
      "linkUnitAddress": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Communication with link unit is OK.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "linkUnitCommunicationFailed",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.159",
    "trap-var-binds": {
      "pduName": 1,
      "pxInetAddressType": 2,
      "pxInetIPAddress": 3,
      "agentInetPortNumber": 4,
      "linkUnitId": 5,
      "linkUnitAddress": 6,
      "sysContact": 7,
      "sysName": 8,
      "sysLocation": 9,
      "pduSerialNumber": 10
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Communication with a link unit failed.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "doorMechanicallyUnlocked",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.160",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "doorHandleName": 6,
      "doorLockName": 7,
      "doorStateName": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A door handle was opened without being electronically unlocked.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "doorForcedOpen",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.161",
    "trap-var-binds": {
      "pduName": 1,
      "pduNumber": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "doorHandleName": 6,
      "doorLockName": 7,
      "doorStateName": 8,
      "sysContact": 9,
      "sysName": 10,
      "sysLocation": 11,
      "pduSerialNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "A door was opened without unlocking the door handle.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  },
  {
    "type": "NO_MIB",
    "trap": "outletServiceModeChanged",
    "trap-oid": "1.3.6.1.4.1.13742.6.0.162",
    "trap-var-binds": {
      "pduName": 1,
      "userName": 2,
      "pxInetAddressType": 3,
      "pxInetIPAddress": 4,
      "agentInetPortNumber": 5,
      "outletLabel": 6,
      "outletServiceMode": 7,
      "sysContact": 8,
      "sysName": 9,
      "sysLocation": 10,
      "pduSerialNumber": 11,
      "pduNumber": 12
    },
    "copy": {},
    "rename": {},
    "set": {
      "status": "critical",
      "description": "Service mode was changed on an outlet.",
      "mib_name": "PDU2-MIB"
    },
    "map-status": {},
    "conditions": [],
    "custom-actions": {},
    "primary": "snmp_source_ip",
    "secondary": "snmp_trap_name"
  }
]