apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bigpanda

resources:
  - rbac.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: bigpanda-agent
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: bigpanda

images:
  - name: reggiejtech/super-agent
    newTag: latest
